# Image Recognition project
INT_CAMERA_RESOLUTION_HEIGHT = 720
INT_CAMERA_RESOLUTION_WEIGHT = 1080
INT_OUT_RESOLUTION_HEIGHT = 480
INT_OUT_RESOLUTION_WEIGHT = 640
INT_MIN_CONF_TRESHOLD = 0.5
INT_WAIT_TIME_SECOND = 0

STR_MODEL_NAME = "Model"
STR_GRAPH_NAME = "detect.tflite"
STR_LABELMAP_NAME = "labelmap.txt"
STR_OBJECTSMAP_NAME = "objects.txt"


# Ultrasonic Sensor project

INT_SOUND_SPEED = 17150
SLEEP_TIME = 0.05
INT_MAX_DISTANCE = 100
INT_MAX_PWM = 1023

ECHO_A = 23
ECHO_B = 2
ECHO_C = 14

TRIG_A = 24
TRIG_B = 3
TRIG_C = 15

MOTOR_A = 13
MOTOR_B = 19
MOTOR_C = 26