# Image Recognition project
INT_CAMERA_RESOLUTION_HEIGHT = 720
INT_CAMERA_RESOLUTION_WEIGHT = 1080
INT_OUT_RESOLUTION_HEIGHT = 480
INT_OUT_RESOLUTION_WEIGHT = 640
INT_MIN_CONF_TRESHOLD = 0.5
INT_WAIT_TIME_SECOND = 0.5

STR_MODEL_NAME = "Model"
STR_GRAPH_NAME = "detect.tflite"
STR_LABELMAP_NAME = "labelmap.txt"
STR_OBJECTSMAP_NAME = "objects.txt"


# Ultrasonic Sensor project

INT_SOUND_SPEED = 17150
INT_SLEEP_TIME = 0.01
INT_WPM_TIME = 0.0001
INT_MAX_DISTANCE = 100

ECHO_A = 24
ECHO_B = 0
ECHO_C = 0

TRIG_A = 23
TRIG_B = 0
TRIG_C = 0

MOTOR_A = 18
MOTOR_B = 0
MOTOR_C = 0 